# Generated by Django 6.0.3 on 2026-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment_availability_delete_car_delete_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('exterior', 'Standard Exterior Detail - $49.99'), ('interior', 'Standard Interior Detail - $59.99'), ('express', 'Standard Express Detail - $99.99'), ('premium', 'Premium Care Detail - $119.99–$169.99'), ('elite', 'Elite Package Detail - $159.99–$219.99')], max_length=50),
        ),
    ]
