# Generated by Django 6.0.3 on 2026-06-06 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='managerEmail',
            field=models.EmailField(default='null', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
        migrations.CreateModel(
            name='ManagerLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manager')),
            ],
        ),
    ]
