# Generated by Django 6.0.3 on 2026-06-06 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_manager_locked_manager_manageremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='managerEmail',
            field=models.EmailField(default='null@null.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
    ]
