# Generated by Django 6.0.3 on 2026-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('exterior', 'Standard Exterior Detail'), ('interior', 'Standard Interior Detail'), ('express', 'Standard Express Detail'), ('premium', 'Premium Care Detail'), ('elite', 'Elite Package Detail')], max_length=50, unique=True)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('suffix', models.CharField(default='per vehicle', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='hours_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availability',
            name='time_length',
            field=models.IntegerField(default=60),
        ),
    ]
