# Generated by Django 6.0.3 on 2026-06-08 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_serviceprice_availability_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='time_length',
            new_name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='hours_length',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('exterior', 'Standard Exterior Detail'), ('interior', 'Standard Interior Detail'), ('express', 'Standard Express Detail'), ('premium', 'Premium Care Detail'), ('elite', 'Elite Package Detail')], max_length=50),
        ),
    ]
