# Generated by Django 6.0.3 on 2026-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_time_length_availability_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
