# Generated by Django 6.0.3 on 2026-06-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_availability_is_primary_serviceprice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='water',
            field=models.TextField(default='no'),
        ),
    ]
